ProjectTest/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('info/', views.info, name='info'),
    path('conocenos/', views.conocenos, name='conocenos'),
    path('servicios/', views.servicios, name='servicios'),
    path('spa/', views.spa, name='spa'),
    path('consulta/', views.consulta, name='consulta'),
    path('viaje/', views.viaje, name='viaje'),
    path('guarderia/', views.guarderia, name='guarderia'),
    path('login/', views.login, name='login'),
    path('autenticacion/', include('prueba1.urls')),
 
    

]

prueba1/urls.py
from django.urls import path
from . import views

app_name = 'autenticacion'
urlpatterns = [
   path('registrarse/', views.signup, name='registrarse'),
   path('registroExitoso/', views.alertSucess, name='registroExitoso'),
    

]

prueba1/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,BaseUserManager, Permission, Group
class CustomUser(AbstractUser):
    name = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    documento =  models.CharField(max_length=30)
    direccion = models.CharField(max_length=100)
    celular = models.CharField(max_length=30)

    groups = models.ManyToManyField(Group, related_name='custom_user_groups')
    user_permissions = models.ManyToManyField(Permission, related_name='custom_user_permissions')

    def __str__(self):
        return self.username


class Cita(models.Model):
    name_owner = models.CharField(max_length=255)
    lastname_owner = models.CharField(max_length=255)
    tel = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    document = models.CharField(max_length=20)
    email = models.EmailField()
    name_pet_id = models.IntegerField()
    name_pet_real = models.CharField(max_length=255)
    color_pet = models.CharField(max_length=50)
    date_birth = models.DateField()
    state_appointment = models.IntegerField()
    service_id = models.IntegerField()
    date_appointment = models.DateField()
    hour_appointment = models.TimeField()

    def __str__(self):
        return f"{self.name_owner} - {self.name_pet_real}"

    class meta:
        verbose_name = "Cita"
        verbose_name_plural = "citas"
        db_table = "Citas"
        ordering = ["service_id"]


class EstadoCita(models.Model):
    state = models.CharField(max_length=255)

    def __str__(self):
        return self.state

    class meta:
        verbose_name = "EstadoCita"
        verbose_name_plural = "estadosCitas"
        db_table = "EstadosCitas"
        ordering = ["state"]


class HistoriaClinica(models.Model):
    name_pet = models.CharField(max_length=255)
    weight_pet = models.DecimalField(max_digits=5, decimal_places=2)
    age_pet = models.IntegerField()
    sterilize_pet = models.BooleanField()
    color_pet = models.CharField(max_length=50)
    medicine_preventive = models.TextField()
    name_owner = models.CharField(max_length=255)
    tel_owner = models.CharField(max_length=20)
    address_owner = models.CharField(max_length=255)
    fc = models.DecimalField(max_digits=5, decimal_places=2)
    fr = models.DecimalField(max_digits=5, decimal_places=2)
    temperature = models.DecimalField(max_digits=5, decimal_places=2)
    fill_capillary = models.DecimalField(max_digits=5, decimal_places=2)
    pulse = models.DecimalField(max_digits=5, decimal_places=2)
    diagnosis_differential = models.TextField()
    diagnosis_final = models.TextField()
    test_laboratory = models.TextField()
    treatment = models.TextField()

    def __str__(self):
        return self.name_pet

    class meta:
        verbose_name = "HistoriaClinica"
        verbose_name_plural = "historiasClinicas"
        db_table = "HistoriasClinicas"
        ordering = ["name_pet"]


class Mascota(models.Model):
    id_pet = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    age = models.IntegerField()
    date_birth = models.DateField()
    color = models.CharField(max_length=50)
    asset = models.BooleanField()

    def __str__(self):
        return self.name

    class meta:
        verbose_name = "Mascota"
        verbose_name_plural = "mascotas"
        db_table = "Mascotas"
        ordering = ["id_pet"]


class Producto(models.Model):
    id_product = models.AutoField(primary_key=True)
    description = models.CharField(max_length=255)
    brand = models.CharField(max_length=50)
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    stock = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    location = models.CharField(max_length=255)
    location = models.DateField()
    image = models.ImageField(upload_to="productos/", blank=True, null=True)

    def __str__(self):
        return self.description

    class meta:
        verbose_name = "Producto"
        verbose_name_plural = "productos"
        db_table = "ProductoS"
        ordering = ["id_product"]


class Servicio(models.Model):
    id_service = models.AutoField(primary_key=True)
    name_service = models.CharField(max_length=255)
    description_service = models.TextField()

    def __str__(self):
        return self.name_service

    class meta:
        verbose_name = "Servicio"
        verbose_name_plural = "Servicios"
        db_table = "Servicios"
        ordering = ["name_service"]


class Raza(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombre

prueba1/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class SignUpForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('name', 'apellido', 'documento', 'direccion', 'celular', 'email', 'password1', 'password2')

ProjectTest/views.py
from django.shortcuts import render
def index(request):
    return render(request,'index.html',{
        #context
    })

def info(request):
    return render(request,'info.html',{
        #context
    })
def conocenos(request):
    return render(request,'conocenos.html',{
        #context
    })
def servicios(request):
    return render(request,'servicios.html',{
        #context
    })
def spa(request):
    return render(request,'spa.html',{
        #context
    })
def consulta(request):
    return render(request,'consulta.html',{
        #context
    })
def viaje(request):
    return render(request,'viaje.html',{
        #context
    })
def guarderia(request):
    return render(request,'guarderia.html',{
        #context
    })
def login(request):
    return render(request,'login.html',{
        #context
    })
def registro(request):
    return render(request,'Auth/registrarse.html',{
        #context
    })

prueba1/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import CustomUser  # Asegúrate de importar tu modelo CustomUser

def signup(request):
    if request.method == 'POST':
        name = request.POST['name']
        apellido = request.POST['apellido']
        documento = request.POST['documento']
        direccion = request.POST['direccion']
        celular = request.POST['celular']
        email = request.POST['email']
        password = request.POST['password']
        password_confirmation = request.POST['password_confirmation']

        if password == password_confirmation:
            # Verifica si el usuario ya existe
            if CustomUser.objects.filter(username=email).exists():
                messages.error(request, 'Ya existe un usuario con este correo electrónico.')
            else:
                # Crear el objeto CustomUser y guardarlo en la base de datos
                user = CustomUser.objects.create_user(username=email, email=email,password=password)
                user.name = name
                user.apellido = apellido
                user.documento = documento
                user.direccion = direccion
                user.celular = celular
                user.save()
                return redirect('autenticacion:registroExitoso')  # Puedes redirigir a la página de inicio de sesión o a donde desee
        else:
            messages.error(request, 'Las contraseñas no coinciden. Intenta nuevamente.')

    return render(request, 'Auth/registrarse.html')

def alertSucess(request):
    return render(request,'alertas/registro_exitoso.html',{
        #context
    })

templates/alertas/alert_register.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style69.css' %}">
    <title>Document</title>
</head>
<body>
    <div id="main-container" class="container-alert">
        <div class="alert-body">
            <div class="container-image">
                <button class="cerrate" id="cloze" onclick="cerrar()">X</button>
                <img class="gif-perro" src="{% static 'img/animal-imagen-animada-0013.gif' %}" alt="gif">
            </div>
            <div class="container-text">
                {% for message in messages %}
                    <span>{{ message }}</span>
                {% endfor %}
            </div>
        </div>
    </div>

</body>
</html>

templates/alertas/registro_exitoso.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro Satisfactorio</title>
    <link rel="stylesheet" href="{% static 'css/style18.css' %}">
</head>
<body>
    <div class="contenedor-general">
        <div class="contenedor-header">
            <header class="contenido-header">
                <img class="img1" src="{% static 'img/best animal2-01 (1).png' %}" alt="">
            </header>
        </div>
        <div class="middle-contenedor">
            <div class="contenido-medio">
                <div class="main-text">TE HAS REGISTRADO SATISFACTORIAMENTE!</div>
                <div class="sub-text">Gracias por registrarse con nosotros, puedes iniciar sesión para mantenerte al tanto de las novedades o regresar a la página de inicio si lo deseas.</div>
                <nav class="botones">
                    <a class="button" href="{% url 'index' %}">IR A INICIO</a>
                    <a class="button" href="{% url 'login' %}">IR A INICIAR SESIÓN</a>
                </nav>
            </div>
        </div>
        <footer class="contendor-footer">
            2022 Clínica Veterinaria Best Animals, todos los derechos reservados
        </footer>
    </div>
</body>
</html>

templates/conocenos.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style19.css' %}">
    <title>Inicio</title>
</head>

<body>
    <div class="contenedor-header">
        <a class="content" href="{% url 'index' %}">
            <img class="logo" src="{% static 'img/best animal2-01 (1).png' %}" alt="logo">
        </a>
    </div>

    <div class="middle-contenedor">
        <div class="middle-row">
            <div class="txt-1">Bienvenido, ten el mejor trato en </div>
            <div class="contenedor-huellas">
                <!-- You can add content here if needed -->
            </div>
        </div>
        <div class="middle-row2">
            <div class="central-txt">BEST ANIMALS</div>
        </div>
        <div class="middle-row3">
            <div class="txt-3">Especialistas en el cuidado de mascotas</div>
            <div class="contenedor-mascotas">
                <img class="mascotas" src="{% static 'img/f8e236c1-01c0-4e15-a6e8-76f25717867d-removebg-preview.png' %}"
                    alt="mascotas">
            </div>
        </div>
    </div>

    <footer class="footer-contenedor">
        <div class="mitad-1">
            <div class="container-gps">
                <a class="put-gps" href="">
                    <img class="imagen" src="{% static 'img/gpsicon_preview_rev_1.png' %}" alt="">
                </a>
            </div>
            <div class="container-text">
                <div class="internal-text">¡Te esperamos!</div>
                <div class="internal-text1">BEST ANIMALS</div>
                <div class="internal-text2">Como llegar a..</div>
            </div>
            <div class="sedes">
                <div class="part">Veterinaria Chía <div class="linea-2"></div>
                </div>
                <div class="part-2">Veterinaria Zipaquirá</div>
            </div>
        </div>
        <div class="linea"></div>
        <div class="mitad-2">
            <div class="container-blackberry">
                <a class="put-phone" href="">
                    <img class="imy" src="{% static 'img/blackberry-removebg-preview.png' %}" alt="teléfono">
                </a>
            </div>
            <div class="comms-container">
                <div class="comms-content">
                    ¡Comunícate! <br> Te respondemos en minutos
                </div>
            </div>
            <div class="container-numeros">
                <div class="divi-1">3229426297 <div class="linea-3"></div>
                </div>
                <div class="divi-2">3163920712</div>
            </div>
        </div>
    </footer>
</body>

</html>

templates/consulta.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consulta Veterinaria</title>
    <link rel="stylesheet" href="{% static 'css/style9.css' %}">
</head>

<body>
    <header class="contenedor1">
        <div class="contenido">
            <nav class="nav_logo">
                <a href="{% url 'index' %}">
                    <img class="img_logo" src="{% static 'img/best animal2-01 (1).png' %}" alt="logo">
                </a>
            </nav>
        </div>
    </header>
    <div class="contenedor2">
        <div class="contf">
            <div class="huellas"></div>
        </div>
        <div class="contletras">
            <p class="maintitle">CONSULTA VETERINARIA</p>
        </div>
        <div class="contf">
            <div class="huellas"></div>
        </div>
    </div>
    <div class="espacio"></div>
    <nav class="contenedor3">
        <div class="box1">
            <header class="tituloo">
                <a class="dentro" href="">Consulta Médica</a>
            </header>
            <div class="contimages">
                <a class="photosurl" href="">
                    <img class="kaw" src="{% static 'img/COnsulta_medica.PNG' %}" alt="consulta">
                </a>
            </div>
        </div>
        <div class="box1">
            <header class="tituloo">
                <a class="dentro" href="">Vacunación y Desparasitación</a>
            </header>
            <div class="contimages">
                <a class="photosurl" href="">
                    <img class="kaw" src="{% static 'img/cat_vacuna.PNG' %}" alt="vacunacion">
                </a>
            </div>
        </div>
        <div class="box1">
            <header class="tituloo">
                <a class="dentro" href="">Cirugía y Hospital</a>
            </header>
            <div class="contimages">
                <a class="photosurl" href="">
                    <img class="kaw" src="{% static 'img/cirujia_hospital.PNG' %}" alt="cirujia">
                </a>
            </div>
        </div>
        <div class="box1">
            <header class="tituloo">
                <a class="dentro" href="">Profilaxis</a>
            </header>
            <div class="contimages">
                <a class="photosurl" href="">
                    <img class="kaw" src="{% static 'img/profi.PNG' %}" alt="cirugia">
                </a>
            </div>
        </div>
    </nav>
</body>

</html>

templates/guarderia.html
<!-- templates/your_app/your_template.html -->
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Guarderia</title>
    <link rel="stylesheet" href="{% static 'CSS/style17.css' %}">
</head>

<body>
    <div class="general-container">
        <header class="contenedor1">
            <div class="contenido">
                <nav class="nav_logo">
                    <a href="{% url 'index' %}">
                        <img class="img_logo" src="{% static 'img/best animal2-01 (1).png' %}" alt="logo">
                    </a>
                </nav>
            </div>
        </header>
        <div class="contenedor2">
            <div class="contletras">
                <div class="mitad-title">GUARDERIA</div>
                <div class="cont-img"><img class="avi"
                        src="{% static 'img/bb5fe413-be69-489e-9f1c-95017d60654d-transformed_preview_rev_1.png' %}"
                        alt=""></div>
            </div>
        </div>
        <div class="subtitle-contenedor">
            <div class="contenido-subtitulo">
                ¿NO TIENES CON QUIEN DEJAR A TU MASCOTA?
            </div>
        </div>
        <div class="container-after-subti">
            <div class="mitad-texto">
                <div class="put-text">No te preocupes, nosotros nos encargamos. En nuestra guardería podrás contar con
                    transporte puerta a puerta, encargados de que tu mascota siga su rutina diaria. Tú eliges el tiempo
                    que requiere para así brindarle un rato acogedor.</div>
            </div>
            <div class="mitad-image">
                <a class="cont-link" href="">
                    <img class="form-img" src="{% static 'img/CASITA-removebg-preview.png' %}" alt="casa">
                </a>
                <a class="description" href="">HAZ CLICK PARA CONTACTARNOS</a>
            </div>
        </div>
    </div>
</body>

</html>

templates/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Best Animals</title>
    <link rel="stylesheet" href="{%static 'css/styleremastered.css'%}">
</head>

<body>
    <header class="contenedor_flex">

        <nav class="contenedor_logo"> <img class="perro" src="{%static 'img/best animal2-01 (1).png'%}" alt="logo">
        </nav>

        <nav class="main_container_botones">
            <div class="contedor_botones"> <a class="put_botones" href="{% url 'conocenos' %}"><img class="tamaño"
                        src="{%static 'img/inicio buttton.png'%}" alt="inicio"> </a>
                <a class="indices" href="{% url 'conocenos' %}">INICIO</a>
            </div>
            <div class="contedor_botones">
                <a class="put_botones" href="{% url 'servicios' %}"> <img class="tamaño"
                        src="{%static 'img/boton 2.jpg'%}" alt="servicios"></a>
                <a class="indices" href="{% url 'servicios' %}">SERVICIOS</a>

            </div>
            <div class="contedor_botones">
                <a class="put_botones" href=""><img class="tamaño" src="{%static 'img/boton 3.png'%}"
                        alt="services"></a>
                <a class="indices" href="">TIENDA ONLINE</a>

            </div>
            <div class="contedor_botones">
                <a class="put_botones" href=""><img class="tamaño" src="{%static 'img/añañin.png'%}" alt="blog"></a>
                <a class="indices" href="">BLOG</a>
            </div>
            <div class="contedor_botones">
                <a class="put_botones" href="{% url 'login' %}"><img class="tamaño" src="{%static 'img/perf.jpg'%}"
                        alt="session"></a>
                <a class="indices" href="{% url 'login' %}">INICAR SESION</a>

            </div>
        </nav>
    </header>

    <div class="middle_contenedor">
        <div class="primera_mitad">
            <div class="titulo">CLINICA VETERINARIA <br>
                BEST ANIMALS</div>
            <div class="segunda_mitad">
                <a class="boton_mascotas" href="{% url 'info' %}">
                    <p id="masc">MASCOTAS <i class="bi bi-arrow-right"></i></p>
                </a>


            </div>


        </div>
        <div class="mitad_perro">
            <img class="dog" src="{%static 'img/perro.jpeg'%}" alt="dog">

        </div>

    </div>

    <footer class="complete">
        <div class="almacenar_redes">
            <a class="put_red" href=""> <img src="{%static 'img/maybe.png'%}" class="cti" alt="instagram"></a>
            <a class="put_red" href=""><img src="{%static 'img/facebook-xxl.png'%}" class="cti1" alt="facebook"></a>
            <a class="put_red" href=""><img src="{%static 'img/whatsapp-xxl.png'%}" class="cti1" alt="whatsapp"></a>

        </div>
        <div class="contenedor_copy">
            2022 Clínica Veterinaria Best Animals, todos los derechos reservados

        </div>

        <footer>


</body>

</html>
</body>

</html>

templates/info.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mascotas</title>
    <link rel="stylesheet" href="{% static 'css/style4.css' %}">
</head>

<body>
    <div class="contentheader">
        <a class="logo" href="{% url 'index' %}">
            <img class="mencion" src="{% static 'img/best animal2-01 (1).png' %}" alt="logo">
        </a>
    </div>
    <div class="maincontainermiddle">
        <div class="contenido1">
            <header class="tittle">
                <p class="internal_text">CONOCE UN POCO DE LA <br> FAMILIA BEST ANIMALS</p>
            </header>
            <div class="texto_centro">
                <p class="texti">En Best Animals Contamos con un equipo de trabajo altamente calificado, más de 18 años
                    de experiencia, con la disposición de dar dosis diarias de amor a tus mascotas. Contamos con equipos
                    tecnológicos de última generación para procedimientos y tratamientos efectivos y brindamos a tus
                    mascotas sus mejores momentos en nuestras manos.</p>
            </div>
            <div class="contener">
                <div class="contener1">
                    <p class="blue">siempre velando por <br> la salud y el bienestar <br> de tu mascota</p>
                </div>
                <div class="contener2">
                    <img class="cora" src="{% static 'img/corzon-removebg-preview.png' %}" alt="">
                </div>
            </div>
        </div>
        <div class="contenido2">
            <header class="logito">
                <img class="redi" src="{% static 'img/best animal2-01 (1).png' %}" alt="">
            </header>
            <div class="contenedorimagenes1">
                <div class="img1">
                    <img class="best1" src="{% static 'img/besto1.PNG' %}" alt="img1">
                </div>
                <div class="img2">
                    <img class="best2" src="{% static 'img/best2.PNG' %}" alt="img2">
                </div>
            </div>
            <div class="contenedorimagenes2">
                <div class="img3">
                    <img class="best3" src="{% static 'img/best3.PNG' %}" alt="img3">
                </div>
                <div class="img4">
                    <img class="cora" src="{% static 'img/deco.PNG' %}" alt="corazao">
                </div>
            </div>
        </div>
    </div>
    <div class="pie">
        <footer class="piess">
            <div class="container_huellas">
                <img class="orange_huellas" src="{% static 'img/orange_huellas-removebg-preview.png' %}" alt="huellas">
            </div>
            <div class="container_dog">
                <img class="canva_perro" src="{% static 'img/canva_perro-removebg-preview.png' %}" alt="">
            </div>
            <div class="container_huellas">
                <img class="orange_huellas" src="{% static 'img/orange_huellas-removebg-preview.png' %}" alt="huellas">
            </div>
        </footer>
    </div>
</body>

</html>

templates/login.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iniciar Sesión</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
</head>

<body>
    <header class="org">
        <div class="cont">
            <a href="{% url 'index' %}"><img class="img5" src="{% static 'img/best animal2-01 (1).png' %}"
                    alt="logo"></a>
        </div>
    </header>
    <div class="ins">
        <div class="cont2">
            <form class="formu" action="" method="post">
                <p class="sesion">INICIAR SESION</p>
                <input class="correo" type="email" name="email" id="correo" placeholder="ej:example@gmail.com" required>
                <input class="correo" type="password" name="password" placeholder="Ingrese su contraseña:" required>
                <br>
                <input class="boton" id="iniciar_sesion" name="ingresar" type="submit" value="Iniciar Sesión">
            </form>
            <p class="not_account">¿No tiene cuenta? <a class="regist" href="{% url 'autenticacion:registrarse' %}">Regístrese
                    aquí</a>
            </p>
            <p class="not_account">¿Olvidó su contraseña?<a class="coloru" href="">Haga
                    clic aquí para recuperarla</a></p>
        </div>
    </div>
    <footer class="fn">
        <div class="tulia">
            <p class="endtext">2022 Clínica Veterinaria Best Animals, todos los derechos reservados</p>
        </div>
    </footer>
</body>

</html>

templates/servicios.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Servicios</title>
    <link rel="stylesheet" href="{% static 'css/style7.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>

<body>
    <header class="contenedor1">
        <div class="contenido">
            <nav class="nav_logo">
                <a href="{% url 'index' %}">
                    <img class="img_logo" src="{% static 'img/best animal2-01 (1).png' %}" alt="logo">
                </a>
            </nav>
        </div>
    </header>
    <div class="middle_contenedor">
        <div class="contenido1">
            <header class="titulo">
                <h3 class="main_tittle">Nuestros Servicios:</h3>
            </header>
            <div class="texto">
                <p class="description">En Best Animals Contamos con un equipo de trabajo altamente calificado, más de 18
                    años de experiencia, con la disposición de dar dosis diarias de amor a tus mascotas. Contamos con
                    equipos tecnológicos de última generación para procedimientos y tratamientos efectivos y brindamos a
                    tus mascotas sus mejores momentos en nuestras manos.</p>
            </div>
        </div>

        <nav class="contenido2">
            <div class="icono">
                <div class="icono_general">
                    <a class="ceta" href="{% url 'spa' %}">
                        <img class="size_images" src="{% static 'img/Boton_Spa-removebg-preview.png' %}" alt="Spa">
                    </a><br>
                    <a class="letter" href="{% url 'spa' %}">SPA</a>
                </div>
                <div class="icono_general">
                    <a class="ceta" href="{% url 'consulta' %}">
                        <img class="size_images" src="{% static 'img/Boton_clinica_veterinaria-removebg-preview.png' %}"
                            alt="clinica">
                    </a><br>
                    <a class="letter" href="{% url 'consulta' %}">CLINICA VETERINARIA</a>
                </div>
            </div>
            <div class="icono">
                <div class="icono_general">
                    <a class="ceta" href="{% url 'viaje' %}">
                        <img class="size_images" src="{% static 'img/Boton_avion-removebg-preview.png' %}" alt="avion">
                    </a><br>
                    <a class="letter" href="{% url 'viaje' %}">CERTIFICADOS DE VIAJE</a>
                </div>
                <div class="icono_general">
                    <a class="ceta" href="{% url 'guarderia' %}">
                        <img class="size_images" src="{% static 'img/Boton_Hospedaje-removebg-preview.png' %}"
                            alt="clinica">
                    </a><br>
                    <a class="letter" href="{% url 'guarderia' %}">HOSPEDAJE</a>
                </div>
            </div>
        </nav>
    </div>

    <footer class="pie">
        <p>2022 clinica best animals todos los derechos reservados</p>
    </footer>
</body>

</html>

templates/spa.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style8.css' %}">
    <title>Spa</title>
</head>

<body>
    <header class="contenedor1">
        <div class="contenido">
            <nav class="nav_logo">
                <a href="{% url 'index' %}">
                    <img class="img_logo" src="{% static 'img/best animal2-01 (1).png' %}" alt="logo">
                </a>
            </nav>
        </div>
    </header>
    <div class="contenedor2">
        <div class="content">
            <h1 class="tittle">PELUQUERIA Y BAÑO</h1>
        </div>
    </div>
    <div class="bubbles">
        <div class="burbus">
            <img class="burbus1" src="{% static 'img/minburbu.PNG' %}" alt="burbujas">
        </div>
        <div class="mensaje">
            <header class="titulo">
                <h1 class="mayus">TARDE DE SPA</h1>
            </header>
            <div class="texts">
                <p class="desc">Si quieres una tarde relajante para tu mascota, contáctanos. Ofrecemos baño completo y
                    medicado, corte higiénico, limpieza de oídos y corte de uñas.</p>
            </div>
        </div>
        <div class="espacio"></div>
        <div class="contdog"> <img class="perro" src="{% static 'img/Mi proyecto (2).png' %}" alt="pug"></div>
    </div>
</body>

</html>